name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt-get update -yqq
        apt-get install -yqq --no-install-recommends build-essential cmake xxd
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
