name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        sudo apt-get update -yqq
        sudo apt-get install -yqq --no-install-recommends build-essential cmake xxd
        rustup update
        rustup component add clippy rustfmt
    - name: Check format
      run: cargo fmt --verbose -- --check
    - name: Run clippy
      run: cargo clippy --verbose -- #-D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
